### ISSUE TITLE
Tagged releases are broken

### ISSUE THREAD

**Issue by peikk0** [kachick/renovate-config-asdf#191]
```
INFO: Repository started (repository=foo/bar)
       "renovateVersion": "32.236.1"
 INFO: Throwing preset error (repository=foo/bar)
       "validationError": "Cannot find preset's package (local>kachick/renovate-config-asdf//plugins/bun.json5#1.4.0). Note: this is a *nested* preset so please contact the preset author if you are unable to fix it yourself."
 INFO: Repository has invalid config (repository=gitlab-com/gl-infra/k8s-workloads/gitlab-helmfiles)
       "error": {
         "validationError": "Cannot find preset's package (local>kachick/renovate-config-asdf//plugins/bun.json5#1.4.0). Note: this is a *nested* preset so please contact the preset author if you are unable to fix it yourself.",
         "message": "config-validation",
         "stack": "Error: config-validation\n    at fetchPreset (/usr/src/app/node_modules/renovate/lib/config/presets/index.ts:370:19)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at resolveConfigPresets (/usr/src/app/node_modules/renovate/lib/config/presets/index.ts:291:31)\n    at Object.resolveConfigPresets (/usr/src/app/node_modules/renovate/lib/config/presets/index.ts:297:30)\n    at mergeRenovateConfig (/usr/src/app/node_modules/renovate/lib/workers/repository/init/merge.ts:225:5)\n    at getRepoConfig (/usr/src/app/node_modules/renovate/lib/workers/repository/init/config.ts:16:12)\n    at initRepo (/usr/src/app/node_modules/renovate/lib/workers/repository/init/index.ts:38:12)\n    at Object.renovateRepository (/usr/src/app/node_modules/renovate/lib/workers/repository/index.ts:43:14)\n    at Object.start (/usr/src/app/node_modules/renovate/lib/workers/global/index.ts:160:7)\n    at /usr/src/app/node_modules/renovate/lib/renovate.ts:16:22"
       }
```

I guess the `#1.4.0` suffix in https://github.com/kachick/renovate-config-asdf/blob/1.4.0/default.json doesn't work with `local` but only with `github`. A possible fix could be to replace `local>` with `github>` then?

**Comment by kachick** [comment]
Thanks for this report!

I have confirmed `local>` prefix working with `"renovateVersion": "32.236.1"` in my repositories in both `1.0.0` and `1.4.0`.
However, I guess this will not work in non GitHub hosted repositories as you say.

So changed to `github>` since version `1.4.1`. I hope this will work in your environtments. 🙏
